### ISSUE TITLE
Supervisor seems to have issues

### ISSUE THREAD

**Issue by jking6884** [lephleg/laravel-lumen-docker#1]
When running docker-compose up I am seeing this issue (screenshot below) with supervisor spawning and exiting nginx and php-fpm until it gives up

![image](https://user-images.githubusercontent.com/4825257/62724129-443a6000-b9e0-11e9-9638-a857ef950fbf.png)

If I docker exec into the app container, both nginx and php-fpm seem to be running.

However, if I try to run:
 php artisan migrate --seed

I get this error:

![image](https://user-images.githubusercontent.com/4825257/62731093-65567d00-b9ef-11e9-9f3a-feae0ed4fbdc.png)

Didn't know if you had any insight on the issue that could be occurring.

**Comment by jking6884** [comment]
I just needed to change 127.0.0.1 to 'mysql' in the .env file

![image](https://user-images.githubusercontent.com/4825257/62740128-e1a78b00-ba04-11e9-8c67-347f7c8ffacb.png)

**Comment by jking6884** [comment]
Does anyone know if the supervisor issue here is normal?

![image](https://user-images.githubusercontent.com/4825257/62740223-3814c980-ba05-11e9-9c35-4ecf39f0f2a8.png)

**Comment by lephleg** [comment]
Hey @jking6884,

Those warnings are by no means fatal, as they don't affect the actual execution as you have already confirmed.

They are produced cause both services are executed using their daemon/background modes. Those states do not return the expected exit codes for the supervisor to verify they are running. So supervisor tries to restart them as it is considering them stuck until it exhausts its maximum attempts and finally gives up. 

I fixed this by switching both services to be executed in their foreground mode. You can fetch the latest changes and rebuild your app image in order to keep your logs clean of those warnings.

**Comment by jking6884** [comment]
@lephleg 

Awesome.  Thanks for pushing that out so quickly.
